#!/bin/bash -eEu

BIN=./tools/bin
VERSION=1.34.0

if [ -z $EXEPATH ]; then
  BUF="https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-Windows-x86_64.exe"
  CMD="$BIN/buf.exe"
else
  BUF="https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-Linux-x86_64"
  CMD="$BIN/buf"
fi

if [ ! -d $BIN ]; then
  mkdir -p tools/bin
  curl -sSL \
  "$BUF" \
  -o "$CMD" && \
  chmod +x "$CMD"  
fi

$CMD lint